/** Auto-generated by scripts/gen-route-permissions.mjs — do not edit by hand. */
import type { PermissionKey } from './permissions';

export const ROUTE_PERMISSIONS: Record<string, PermissionKey[]> = {
  "AccessoriesController.list": [
    "asset:read"
  ],
  "AccessoriesController.get": [
    "asset:read"
  ],
  "AccessoriesController.create": [
    "asset:create"
  ],
  "AccessoriesController.update": [
    "asset:update"
  ],
  "AccessoriesController.checkout": [
    "asset:read"
  ],
  "AccessoriesController.checkin": [
    "asset:read"
  ],
  "AccessoriesController.adjustStock": [
    "asset:read"
  ],
  "AssetRequestsController.create": [
    "asset:create"
  ],
  "AssetRequestsController.review": [
    "asset:read"
  ],
  "AssetRequestsController.fulfill": [
    "asset:update",
    "maintenance:manage"
  ],
  "AssetsController.labels": [
    "asset:export"
  ],
  "AssetsController.create": [
    "asset:create"
  ],
  "AssetsController.duplicate": [
    "asset:read"
  ],
  "AssetsController.bulk": [
    "asset:read"
  ],
  "AssetsController.auditByCode": [
    "audit:read"
  ],
  "AssetsController.update": [
    "asset:update"
  ],
  "AssetsController.assign": [
    "asset:update"
  ],
  "AssetsController.audit": [
    "audit:read"
  ],
  "AssetsController.transfer": [
    "asset:update"
  ],
  "AssetsController.retire": [
    "asset:update"
  ],
  "AssetsController.changeStatus": [
    "asset:read"
  ],
  "AssetsController.remove": [
    "user:manage"
  ],
  "IssueKitsController.list": [
    "asset:read"
  ],
  "IssueKitsController.get": [
    "asset:read"
  ],
  "IssueKitsController.create": [
    "asset:create"
  ],
  "IssueKitsController.update": [
    "asset:update"
  ],
  "IssueKitsController.remove": [
    "asset:delete"
  ],
  "IssueKitsController.issue": [
    "asset:read"
  ],
  "AuditController.exportCsv": [
    "audit:read"
  ],
  "AuditController.list": [
    "audit:read"
  ],
  "AuditCyclesController.list": [
    "audit:read"
  ],
  "AuditCyclesController.get": [
    "audit:read"
  ],
  "AuditCyclesController.export": [
    "audit:read"
  ],
  "AuditCyclesController.create": [
    "audit:read"
  ],
  "AuditCyclesController.update": [
    "audit:read"
  ],
  "AuditCyclesController.start": [
    "audit:read"
  ],
  "AuditCyclesController.close": [
    "audit:read"
  ],
  "AuditCyclesController.addFinding": [
    "audit:read"
  ],
  "AuditCyclesController.resolveFinding": [
    "audit:read"
  ],
  "AuthController.beginMfaSetup": [
    "user:manage"
  ],
  "AuthController.beginMfaSetupAlias": [
    "user:manage"
  ],
  "AuthController.enableMfa": [
    "user:manage"
  ],
  "AuthController.disableMfa": [
    "user:manage"
  ],
  "CategoriesController.list": [
    "category:manage"
  ],
  "CategoriesController.get": [
    "category:manage"
  ],
  "CategoriesController.create": [
    "category:manage"
  ],
  "CategoriesController.update": [
    "category:manage"
  ],
  "CategoriesController.remove": [
    "category:manage"
  ],
  "ChatController.staff": [
    "ticket:manage"
  ],
  "ChatController.unread": [
    "ticket:manage"
  ],
  "ChatController.presence": [
    "ticket:manage"
  ],
  "ChatController.setPresence": [
    "ticket:manage"
  ],
  "ChatController.ping": [
    "ticket:manage"
  ],
  "ChatController.search": [
    "ticket:manage"
  ],
  "ChatController.mentions": [
    "ticket:manage"
  ],
  "ChatController.readAll": [
    "ticket:manage"
  ],
  "ChatController.channels": [
    "ticket:manage"
  ],
  "ChatController.createChannel": [
    "ticket:manage"
  ],
  "ChatController.dm": [
    "ticket:manage"
  ],
  "ChatController.group": [
    "ticket:manage"
  ],
  "ChatController.channel": [
    "ticket:manage"
  ],
  "ChatController.patchChannel": [
    "ticket:manage"
  ],
  "ChatController.join": [
    "ticket:manage"
  ],
  "ChatController.leave": [
    "ticket:manage"
  ],
  "ChatController.addMembers": [
    "ticket:manage"
  ],
  "ChatController.removeMember": [
    "ticket:manage"
  ],
  "ChatController.prefs": [
    "ticket:manage"
  ],
  "ChatController.messages": [
    "ticket:manage"
  ],
  "ChatController.thread": [
    "ticket:manage"
  ],
  "ChatController.post": [
    "ticket:manage"
  ],
  "ChatController.read": [
    "ticket:manage"
  ],
  "ChatController.edit": [
    "ticket:manage"
  ],
  "ChatController.remove": [
    "ticket:delete"
  ],
  "ChatController.react": [
    "ticket:manage"
  ],
  "ChatController.unreact": [
    "ticket:manage"
  ],
  "ChatController.attachment": [
    "ticket:manage"
  ],
  "ClientsController.list": [
    "asset:read"
  ],
  "ClientsController.create": [
    "asset:create"
  ],
  "ClientsController.update": [
    "asset:update"
  ],
  "ClientsController.listVdi": [
    "asset:read"
  ],
  "ClientsController.createVdi": [
    "asset:create"
  ],
  "ClientsController.assign": [
    "asset:update"
  ],
  "ClientsController.ticketSummary": [
    "asset:read"
  ],
  "ConsumablesController.list": [
    "asset:read"
  ],
  "ConsumablesController.get": [
    "asset:read"
  ],
  "ConsumablesController.create": [
    "asset:create"
  ],
  "ConsumablesController.update": [
    "asset:update"
  ],
  "ConsumablesController.issue": [
    "asset:read"
  ],
  "ConsumablesController.adjustStock": [
    "asset:read"
  ],
  "CustomRolesController.catalog": [
    "user:manage"
  ],
  "CustomRolesController.list": [
    "user:manage"
  ],
  "CustomRolesController.create": [
    "user:manage"
  ],
  "CustomRolesController.update": [
    "user:manage"
  ],
  "CustomRolesController.remove": [
    "user:manage"
  ],
  "DashboardController.metrics": [
    "report:run"
  ],
  "DashboardController.setup": [
    "report:read"
  ],
  "DashboardController.trends": [
    "report:read"
  ],
  "DashboardController.byLocation": [
    "report:read"
  ],
  "DashboardController.warrantyExpiring": [
    "report:read"
  ],
  "DashboardController.tickets": [
    "report:read"
  ],
  "DashboardController.attention": [
    "report:read"
  ],
  "DashboardController.teamSummary": [
    "report:run"
  ],
  "DepartmentsController.list": [
    "department:manage"
  ],
  "DepartmentsController.get": [
    "department:manage"
  ],
  "DepartmentsController.create": [
    "department:manage"
  ],
  "DepartmentsController.update": [
    "department:manage"
  ],
  "DepartmentsController.remove": [
    "department:manage"
  ],
  "ChecklistsController.templates": [
    "employee:read"
  ],
  "ChecklistsController.updateTemplate": [
    "employee:manage"
  ],
  "ChecklistsController.createTemplate": [
    "employee:create"
  ],
  "ChecklistsController.start": [
    "employee:read"
  ],
  "ChecklistsController.toggle": [
    "employee:read"
  ],
  "EmployeesController.exportPersonalData": [
    "user:manage"
  ],
  "EmployeesController.offboard": [
    "employee:manage"
  ],
  "EmployeesController.reinstate": [
    "employee:manage"
  ],
  "EmployeesController.createLogin": [
    "employee:create"
  ],
  "EmployeesController.create": [
    "employee:create"
  ],
  "EmployeesController.update": [
    "employee:manage"
  ],
  "EmployeesController.remove": [
    "user:manage"
  ],
  "FeedbackController.list": [
    "asset:read"
  ],
  "ImportExportController.exportAssets": [
    "asset:export"
  ],
  "ImportExportController.exportEmployees": [
    "asset:export"
  ],
  "ImportExportController.importAssets": [
    "asset:import"
  ],
  "ImportExportController.importEmployees": [
    "asset:import"
  ],
  "ImportJobsController.list": [
    "asset:read"
  ],
  "ImportJobsController.get": [
    "asset:read"
  ],
  "ImportJobsController.create": [
    "asset:create"
  ],
  "ImportJobsController.preview": [
    "asset:read"
  ],
  "ImportJobsController.commit": [
    "asset:update"
  ],
  "ImportJobsController.rollback": [
    "asset:read"
  ],
  "LocationsController.list": [
    "location:manage"
  ],
  "LocationsController.get": [
    "location:manage"
  ],
  "LocationsController.summary": [
    "location:manage"
  ],
  "LocationsController.create": [
    "location:manage"
  ],
  "LocationsController.update": [
    "location:manage"
  ],
  "LocationsController.remove": [
    "location:manage"
  ],
  "MaintenanceController.list": [
    "maintenance:read"
  ],
  "MaintenanceController.get": [
    "maintenance:read"
  ],
  "MaintenanceController.fileOemClaim": [
    "maintenance:read"
  ],
  "MaintenanceController.update": [
    "maintenance:manage"
  ],
  "MaintenanceController.transition": [
    "maintenance:read"
  ],
  "NotesController.list": [
    "asset:read"
  ],
  "NotesController.create": [
    "asset:create"
  ],
  "NotificationsController.runWarrantyCheck": [
    "ticket:manage"
  ],
  "ContractsController.list": [
    "procurement:read"
  ],
  "ContractsController.forAsset": [
    "procurement:manage"
  ],
  "ContractsController.history": [
    "procurement:manage"
  ],
  "ContractsController.get": [
    "procurement:read"
  ],
  "ContractsController.create": [
    "procurement:manage"
  ],
  "ContractsController.update": [
    "procurement:manage"
  ],
  "ContractsController.renew": [
    "procurement:manage"
  ],
  "ContractsController.meta": [
    "report:run"
  ],
  "ContractsController.matrix": [
    "procurement:manage"
  ],
  "ContractsController.invoices": [
    "procurement:manage"
  ],
  "ContractsController.summary": [
    "procurement:read"
  ],
  "ContractsController.runRenewals": [
    "procurement:manage"
  ],
  "PurchaseOrdersController.list": [
    "procurement:read"
  ],
  "PurchaseOrdersController.pdf": [
    "procurement:export"
  ],
  "PurchaseOrdersController.history": [
    "procurement:manage"
  ],
  "PurchaseOrdersController.get": [
    "procurement:read"
  ],
  "PurchaseOrdersController.convert": [
    "procurement:manage"
  ],
  "PurchaseOrdersController.send": [
    "procurement:manage"
  ],
  "PurchaseOrdersController.amend": [
    "procurement:read"
  ],
  "PurchaseOrdersController.cancel": [
    "procurement:manage"
  ],
  "PurchaseOrdersController.shortClose": [
    "procurement:manage"
  ],
  "PurchaseOrdersController.receive": [
    "procurement:manage"
  ],
  "PurchaseOrdersController.voidReceipt": [
    "procurement:manage"
  ],
  "PurchaseOrdersController.invoice": [
    "procurement:manage"
  ],
  "PurchaseOrdersController.payment": [
    "procurement:read"
  ],
  "RequisitionsController.list": [
    "procurement:read"
  ],
  "RequisitionsController.history": [
    "procurement:manage"
  ],
  "RequisitionsController.get": [
    "procurement:read"
  ],
  "RequisitionsController.create": [
    "procurement:manage"
  ],
  "RequisitionsController.update": [
    "procurement:manage"
  ],
  "RequisitionsController.submit": [
    "procurement:manage"
  ],
  "RequisitionsController.decide": [
    "procurement:manage"
  ],
  "RequisitionsController.cancel": [
    "procurement:manage"
  ],
  "RequisitionsController.attach": [
    "procurement:manage"
  ],
  "VendorsController.list": [
    "procurement:read"
  ],
  "VendorsController.options": [
    "procurement:manage"
  ],
  "VendorsController.history": [
    "procurement:manage"
  ],
  "VendorsController.kpis": [
    "procurement:manage"
  ],
  "VendorsController.get": [
    "procurement:read"
  ],
  "VendorsController.create": [
    "procurement:manage"
  ],
  "VendorsController.update": [
    "procurement:manage"
  ],
  "VendorsController.status": [
    "procurement:manage"
  ],
  "VendorsController.approveBank": [
    "procurement:manage"
  ],
  "VendorsController.scorecard": [
    "procurement:manage"
  ],
  "VendorsController.compliance": [
    "procurement:manage"
  ],
  "ReconciliationController.list": [
    "audit:read"
  ],
  "ReconciliationController.get": [
    "audit:read"
  ],
  "ReconciliationController.run": [
    "audit:read"
  ],
  "RecordsController.manual": [
    "audit:read"
  ],
  "RecordsController.backfillAssignment": [
    "audit:read"
  ],
  "RecordsController.backfillMaintenance": [
    "audit:read"
  ],
  "ReportsController.report": [
    "report:run"
  ],
  "SavedViewsController.list": [
    "asset:read"
  ],
  "SavedViewsController.create": [
    "asset:create"
  ],
  "SavedViewsController.update": [
    "asset:update",
    "maintenance:manage"
  ],
  "SavedViewsController.remove": [
    "asset:delete"
  ],
  "SearchController.search": [
    "asset:read"
  ],
  "TenantController.branding": [
    "user:manage"
  ],
  "TenantController.loadSample": [
    "user:manage"
  ],
  "TenantController.export": [
    "user:manage"
  ],
  "TenantController.billing": [
    "user:manage"
  ],
  "TenantController.close": [
    "user:manage"
  ],
  "EmailInboxController.status": [
    "ticket:manage"
  ],
  "EmailInboxController.test": [
    "user:manage"
  ],
  "EmailInboxController.poll": [
    "user:manage"
  ],
  "EmailInboxController.ingestStaff": [
    "ticket:manage"
  ],
  "TicketsController.reports": [
    "ticket:export"
  ],
  "TicketsController.exportTickets": [
    "ticket:export"
  ],
  "TicketsController.exportReports": [
    "ticket:export"
  ],
  "TicketsController.staff": [
    "ticket:manage"
  ],
  "TicketsController.upsertCategory": [
    "ticket:manage"
  ],
  "TicketsController.canned": [
    "ticket:manage"
  ],
  "TicketsController.createCanned": [
    "ticket:manage"
  ],
  "TicketsController.updateCanned": [
    "ticket:manage"
  ],
  "TicketsController.deleteCanned": [
    "ticket:delete"
  ],
  "TicketsController.createTemplate": [
    "ticket:manage"
  ],
  "TicketsController.updateTemplate": [
    "ticket:manage"
  ],
  "TicketsController.deleteTemplate": [
    "ticket:delete"
  ],
  "TicketsController.bulkAssign": [
    "ticket:manage"
  ],
  "TicketsController.bulkClose": [
    "ticket:manage"
  ],
  "TicketsController.notifyPref": [
    "ticket:manage"
  ],
  "TicketsController.runDigest": [
    "ticket:manage"
  ],
  "TicketsController.linkAsset": [
    "ticket:manage"
  ],
  "TicketsController.priorityTargets": [
    "ticket:manage"
  ],
  "TicketsController.savePriorityTargets": [
    "ticket:manage"
  ],
  "TicketsController.create": [
    "ticket:manage"
  ],
  "TicketsController.assign": [
    "ticket:manage"
  ],
  "TicketsController.assignToMe": [
    "ticket:manage"
  ],
  "TicketsController.presence": [
    "ticket:manage"
  ],
  "TicketsController.transition": [
    "ticket:manage"
  ],
  "TicketsController.removeWatcher": [
    "ticket:manage"
  ],
  "TicketsController.logTime": [
    "ticket:manage"
  ],
  "TicketsController.duplicate": [
    "ticket:manage"
  ],
  "TicketsController.applyTemplate": [
    "ticket:manage"
  ],
  "TicketsController.verifyIdentity": [
    "ticket:manage"
  ],
  "TicketsController.sendResetLink": [
    "ticket:manage"
  ],
  "TicketsController.recordIdpReset": [
    "ticket:manage"
  ],
  "UsersController.list": [
    "user:manage"
  ],
  "UsersController.get": [
    "user:manage"
  ],
  "UsersController.create": [
    "user:manage"
  ],
  "UsersController.update": [
    "user:manage"
  ],
  "UsersController.resetPassword": [
    "user:manage"
  ],
  "WebhooksController.list": [
    "user:manage"
  ],
  "WebhooksController.get": [
    "user:manage"
  ],
  "WebhooksController.create": [
    "user:manage"
  ],
  "WebhooksController.update": [
    "user:manage"
  ],
  "WebhooksController.remove": [
    "user:manage"
  ]
} as unknown as Record<string, PermissionKey[]>;
